import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';
import AboutMe from '@/components/AboutMe';
import ProjectsOverview from '@/components/ProjectsOverview';
import Contact from '@/components/Contact';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-gray-100 text-gray-900">
        <main>
          <Navbar />
          {children}
          <AboutMe />
          <ProjectsOverview />
          <Contact />
          <Footer />
        </main>
      </body>
    </html>
  );
}
